import type { SubtitleTrack, VideoQualityOption } from '@/lib/types';

type UnknownRecord = Record<string, unknown>;

function isRecord(value: unknown): value is UnknownRecord {
    return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function asString(value: unknown): string | undefined {
    if (typeof value === 'string' && value.trim()) return value.trim();
    if (typeof value === 'number' && Number.isFinite(value)) return String(value);
    return undefined;
}

function asNumber(value: unknown): number | undefined {
    if (typeof value === 'number' && Number.isFinite(value)) return value;
    if (typeof value === 'string' && value.trim()) {
        const parsed = Number(value);
        if (Number.isFinite(parsed)) return parsed;
    }
    return undefined;
}

function getFirstString(record: UnknownRecord, keys: string[]): string | undefined {
    for (const key of keys) {
        const value = asString(record[key]);
        if (value) return value;
    }
    return undefined;
}

function getFirstNumber(record: UnknownRecord, keys: string[]): number | undefined {
    for (const key of keys) {
        const value = asNumber(record[key]);
        if (value !== undefined) return value;
    }
    return undefined;
}

function normalizeQualityEntry(value: unknown): VideoQualityOption | null {
    if (typeof value === 'string') {
        return value.trim() ? { quality: value.trim(), label: value.trim() } : null;
    }
    if (!isRecord(value)) return null;

    const vcodec = getFirstString(value, ['vcodec', 'videoCodec', 'video_codec']);
    if (vcodec?.toLowerCase() === 'none') return null;

    const height = getFirstNumber(value, ['height', 'videoHeight', 'video_height']);
    const width = getFirstNumber(value, ['width', 'videoWidth', 'video_width']);
    const fps = getFirstNumber(value, ['fps', 'frameRate', 'frame_rate']);
    const formatIdValue = getFirstNumber(value, ['formatId', 'format_id', 'itag']);
    const filesize = getFirstNumber(value, ['filesize', 'fileSize', 'filesize_approx', 'contentLength']);
    const ext = getFirstString(value, ['ext', 'container', 'extension']);
    const acodec = getFirstString(value, ['acodec', 'audioCodec', 'audio_codec']);
    const directUrl = getFirstString(value, ['downloadUrl', 'download_url', 'url', 'baseUrl', 'base_url']);
    const explicitQuality = getFirstString(value, ['quality', 'qualityId', 'quality_id', 'resolution']);
    const quality = explicitQuality || (height ? String(height) : undefined) || (formatIdValue ? String(formatIdValue) : undefined);

    if (!quality) return null;

    // Preserve an explicit user-facing label exactly as returned by the parser.
    // Only synthesize a richer label when the backend did not provide one.
    const explicitLabel = getFirstString(value, ['label']);
    const formatLabel = getFirstString(value, ['formatNote', 'format_note', 'format']);
    const labelParts = [
        formatLabel,
        height ? `${height}p${fps && fps > 30 ? Math.round(fps) : ''}` : undefined,
        ext?.toUpperCase(),
    ].filter(Boolean);

    return {
        quality,
        label: explicitLabel || labelParts.join(' · ') || quality,
        width,
        height,
        fps,
        formatId: formatIdValue,
        filesize,
        ext,
        vcodec,
        acodec,
        downloadUrl: directUrl,
    };
}

function normalizeQualityArray(value: unknown): VideoQualityOption[] | undefined {
    if (!Array.isArray(value)) return undefined;
    const options = value.map(normalizeQualityEntry).filter((item): item is VideoQualityOption => Boolean(item));
    return options.length ? options : undefined;
}

function subtitleEntryFromRecord(
    value: UnknownRecord,
    language: string,
    index: number,
    isAutoGenerated: boolean
): SubtitleTrack | null {
    const url = getFirstString(value, ['downloadUrl', 'download_url', 'url']);
    if (!url) return null;
    return {
        id: getFirstString(value, ['id']) || `${language}-${isAutoGenerated ? 'auto' : 'manual'}-${index}`,
        language,
        label: getFirstString(value, ['label', 'name', 'displayName', 'display_name']) || language,
        url,
        downloadUrl: getFirstString(value, ['downloadUrl', 'download_url']),
        format: getFirstString(value, ['format', 'ext']),
        isAutoGenerated,
    };
}

function normalizeSubtitleArray(value: unknown, defaultLanguage = 'und', isAutoGenerated = false): SubtitleTrack[] {
    if (!Array.isArray(value)) return [];
    return value.flatMap((entry, index) => {
        if (typeof entry === 'string') {
            return [{
                id: `${defaultLanguage}-${isAutoGenerated ? 'auto' : 'manual'}-${index}`,
                language: defaultLanguage,
                label: defaultLanguage,
                url: entry,
                isAutoGenerated,
            } satisfies SubtitleTrack];
        }
        if (!isRecord(entry)) return [];
        const language = getFirstString(entry, ['language', 'lang', 'languageCode', 'language_code']) || defaultLanguage;
        const track = subtitleEntryFromRecord(entry, language, index, isAutoGenerated);
        return track ? [track] : [];
    });
}

function normalizeSubtitleMap(value: unknown, isAutoGenerated = false): SubtitleTrack[] {
    if (Array.isArray(value)) return normalizeSubtitleArray(value, 'und', isAutoGenerated);
    if (!isRecord(value)) return [];

    const tracks: SubtitleTrack[] = [];
    for (const [language, entries] of Object.entries(value)) {
        if (typeof entries === 'string') {
            tracks.push({
                id: `${language}-${isAutoGenerated ? 'auto' : 'manual'}-0`,
                language,
                label: language,
                url: entries,
                isAutoGenerated,
            });
            continue;
        }

        if (Array.isArray(entries)) {
            tracks.push(...normalizeSubtitleArray(entries, language, isAutoGenerated));
            continue;
        }

        if (isRecord(entries)) {
            const track = subtitleEntryFromRecord(entries, language, 0, isAutoGenerated);
            if (track) tracks.push(track);
        }
    }
    return tracks;
}

function dedupeSubtitles(tracks: SubtitleTrack[]): SubtitleTrack[] {
    const seen = new Set<string>();
    return tracks.filter((track) => {
        const url = track.downloadUrl || track.url || '';
        const key = `${track.language}|${track.format || ''}|${url}`;
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
    });
}

/**
 * Compatible parser deployments may expose yt-dlp-like `formats`,
 * `subtitles`, or `automatic_captions` fields. Normalize those optional
 * shapes into the stable frontend model without requiring a backend-specific
 * UI implementation.
 */
export function normalizeParserCapabilities<T extends UnknownRecord>(data: T): T & {
    qualityOptions?: VideoQualityOption[];
    subtitles?: SubtitleTrack[];
} {
    const existingQuality = normalizeQualityArray(data.qualityOptions);
    const qualityOptions = existingQuality
        || normalizeQualityArray(data.videoFormats)
        || normalizeQualityArray(data.video_formats)
        || normalizeQualityArray(data.formats)
        || normalizeQualityArray(data.qualities);

    const existingSubtitles = normalizeSubtitleMap(data.subtitles, false);
    const captions = normalizeSubtitleMap(data.captions, false);
    const autoCaptions = normalizeSubtitleMap(data.automatic_captions ?? data.automaticCaptions, true);
    const subtitles = dedupeSubtitles([...existingSubtitles, ...captions, ...autoCaptions]);

    return {
        ...data,
        ...(qualityOptions?.length ? { qualityOptions } : {}),
        ...(subtitles.length ? { subtitles } : {}),
    };
}
