/**
 * 统一接口类型定义
 */

export const API_ERROR_CODES = [
    'BAD_REQUEST',
    'INVALID_JSON',
    'UNSUPPORTED_PLATFORM',
    'PLATFORM_MISMATCH',
    'INVALID_DOWNLOAD_TYPE',
    'INVALID_QUALITY',
    'NOT_FOUND',
    'DOWNLOAD_URL_NOT_FOUND',
    'RATE_LIMITED',
    'UPSTREAM_ERROR',
    'SERVICE_UNAVAILABLE',
    'INTERNAL_ERROR',
    'FEEDBACK_SUBMIT_FAILED',
    'MEDIA_PROCESSOR_INIT_FAILED',
    'PARSE_FAILED',
] as const

export type ApiErrorCode = (typeof API_ERROR_CODES)[number]
export type ApiErrorDetails = Record<string, unknown>
export type VideoAudioMode = 'muxed' | 'separate' | 'pure_music' | 'not_applicable'
export type ResultKind = 'video' | 'audio' | 'picker' | 'image'
export type WebDocumentType = 'post' | 'article' | 'product' | 'gallery' | 'webpage'

export interface PodcastEpisodeInfo {
    id: string;
    title: string;
    cover?: string | null;
    duration?: number;
    releaseDate?: string;
    downloadAudioUrl?: string | null;
    originDownloadAudioUrl?: string | null;
}

export type VideoMediaAction = 'direct-download' | 'merge-then-download' | 'browser-hls-download' | 'hide'
export type AudioMediaAction = 'direct-download' | 'extract-audio' | 'hide'

export interface MediaActions {
    video: VideoMediaAction;
    audio: AudioMediaAction;
}

export interface VideoQualityOption {
    /** Canonical value accepted by the download API, for example best / 1080 / 1080p. */
    quality: string;
    label?: string;
    width?: number;
    height?: number;
    formatId?: number;
    /** Optional direct stream for this exact format when the parser exposes it. */
    downloadUrl?: string | null;
    /** Optional estimated byte size returned by a parser. */
    filesize?: number | null;
    /** Optional codec/container metadata used only for display. */
    ext?: string;
    vcodec?: string;
    acodec?: string;
    fps?: number;
}

export interface SubtitleTrack {
    id?: string;
    language: string;
    label?: string;
    url?: string | null;
    downloadUrl?: string | null;
    format?: string;
    isAutoGenerated?: boolean;
}

/**
 * 多P视频的单个分P信息
 */
export interface PageInfo {
    page: number;
    cid: string;
    part: string;
    duration: number;
    downloadAudioUrl: string | null;
    downloadVideoUrl: string | null;
    videoAudioMode?: VideoAudioMode;
    qualityOptions?: VideoQualityOption[];
    subtitles?: SubtitleTrack[];
}

export interface EmbeddedVideoInfo {
    id: string;
    title: string;
    cover?: string | null;
    duration?: number;
    qualityOptions?: VideoQualityOption[];
    subtitles?: SubtitleTrack[];
    downloadVideoUrl?: string | null;
    downloadAudioUrl?: string | null;
    originDownloadVideoUrl?: string | null;
    originDownloadAudioUrl?: string | null;
    videoAudioMode?: VideoAudioMode;
    mediaActions?: MediaActions;
}

export interface UnifiedParseResultImage {
    index?: number;
    url?: string | null;
    downloadUrl?: string | null;
}

export interface UnifiedParseResult {
    success: boolean;
    code?: ApiErrorCode | string;
    status?: number;
    requestId?: string;
    details?: ApiErrorDetails;
    data?: {
        title: string;
        desc?: string;
        /** Full post/article text when the parser can extract more than a short description. */
        textContent?: string;
        author?: string;
        publishedAt?: string;
        siteName?: string;
        documentType?: WebDocumentType;
        cover?: string | null;
        platform: string;
        downloadAudioUrl: string | null;
        downloadVideoUrl: string | null;
        originDownloadAudioUrl?: string | null;
        originDownloadVideoUrl: string | null;
        videoAudioMode?: VideoAudioMode;
        mediaActions?: MediaActions;
        /** Available resolutions/formats when the parser exposes them. */
        qualityOptions?: VideoQualityOption[];
        /** Manual or auto-generated subtitle tracks when available. */
        subtitles?: SubtitleTrack[];
        url: string;
        // 时长（秒）
        duration?: number;
        // 多P视频相关字段
        isMultiPart?: boolean;
        currentPage?: number;
        currentItemId?: string;
        pages?: PageInfo[];
        // 小红书/抖音/网页图文相关字段
        noteType?: 'video' | 'image' | 'audio';
        images?: Array<string | UnifiedParseResultImage>;
        // 微信公众号文章、商品页、普通网页中的嵌入视频列表
        videos?: EmbeddedVideoInfo[];
        // 结果类型（picker = 多集选择器，如 Apple Podcasts 节目页）
        kind?: ResultKind;
        // Apple Podcasts 单集列表
        episodes?: PodcastEpisodeInfo[];
        currentEpisodeId?: string;
    };
    error?: string;
    message?: string;
    url?: string; // 错误时可能包含原始URL
}

export interface UnifiedDownloadOptions {
    format: 'audio' | 'video';
    quality?: string;
}

export interface UnifiedApiResponse<T = unknown> {
    success: boolean;
    data?: T;
    code?: ApiErrorCode | string;
    status?: number;
    requestId?: string;
    details?: ApiErrorDetails;
    error?: string;
    message?: string;
}

export type Platform =
    | 'bili'
    | 'bilibili'
    | 'bilibili_tv'
    | 'dailymotion'
    | 'douyin'
    | 'kuaishou'
    | 'newgrounds'
    | 'okru'
    | 'pinterest'
    | 'reddit'
    | 'soundcloud'
    | 'streamable'
    | 'twitch'
    | 'tumblr'
    | 'youtube'
    | 'telegram'
    | 'threads'
    | 'vk'
    | 'vimeo'
    | 'wechat'
    | 'nico'
    | 'niconico'
    | 'weibo'
    | 'xiaohongshu'
    | 'tiktok'
    | 'instagram'
    | 'ins'
    | 'x'
    | 'twitter'
    | 'apple_podcasts'
    | 'unknown';