import { describe, expect, it } from 'vitest'

import {
    buildSourceMediaDownloadUrl,
    createMediaMetadata,
    getSubtitleDisplayName,
    inferExtension,
    normalizeQualityOptions,
    resolveSubtitleUrl,
} from '../src/lib/media-download-options.ts'

describe('advanced media download helpers', () => {
    it('builds a fresh source-aware video request with quality', () => {
        const url = buildSourceMediaDownloadUrl({
            sourceUrl: 'https://youtu.be/example?list=abc',
            type: 'video',
            quality: '1080',
            formatId: 137,
        })

        const parsed = new URL(url, 'https://app.example.com')
        expect(parsed.pathname).toBe('/api/download')
        expect(parsed.searchParams.get('url')).toBe('https://youtu.be/example?list=abc')
        expect(parsed.searchParams.get('type')).toBe('video')
        expect(parsed.searchParams.get('quality')).toBe('1080')
        expect(parsed.searchParams.get('formatId')).toBe('137')
    })

    it('uses common high-resolution presets when the parser exposes no formats', () => {
        const options = normalizeQualityOptions()
        expect(options[0].quality).toBe('best')
        expect(options.some((item) => item.height === 2160)).toBe(true)
        expect(options.some((item) => item.height === 1080)).toBe(true)
        expect(options.some((item) => item.height === 720)).toBe(true)
    })

    it('prefers and sorts parser-provided formats', () => {
        const options = normalizeQualityOptions([
            { quality: '720p', height: 720, filesize: 10_000 },
            { quality: '2160p', height: 2160, filesize: 50_000 },
            { quality: '1080p60', height: 1080, fps: 60 },
        ])

        expect(options[0].quality).toBe('best')
        expect(options[1].quality).toBe('2160p')
        expect(options[2].quality).toBe('1080p60')
        expect(options[3].quality).toBe('720p')
        expect(options.slice(1).every((item) => item.source === 'parser')).toBe(true)
    })

    it('resolves subtitle URLs and labels auto-generated tracks', () => {
        const track = {
            language: 'en',
            label: 'English',
            downloadUrl: 'https://cdn.example.com/subtitle.vtt',
            isAutoGenerated: true,
        }
        expect(resolveSubtitleUrl(track)).toBe('https://cdn.example.com/subtitle.vtt')
        expect(getSubtitleDisplayName(track)).toBe('English · auto')
    })

    it('infers cover/subtitle extensions without trusting query strings', () => {
        expect(inferExtension('https://cdn.example.com/thumb.webp?token=x', 'jpg')).toBe('webp')
        expect(inferExtension('https://cdn.example.com/caption?id=1', 'vtt')).toBe('vtt')
    })

    it('exports non-destructive media metadata', () => {
        const metadata = createMediaMetadata({
            title: 'Example',
            platform: 'youtube',
            url: 'https://youtu.be/example',
            duration: 42,
            cover: 'https://img.example.com/cover.jpg',
            qualityOptions: [{ quality: '1080', height: 1080 }],
            subtitles: [{ language: 'en', url: 'https://cdn.example.com/en.vtt' }],
        })

        expect(metadata.title).toBe('Example')
        expect(metadata.durationSeconds).toBe(42)
        expect(metadata.qualityOptions).toHaveLength(1)
        expect(metadata.subtitles).toHaveLength(1)
        expect(metadata.exportedAt).toMatch(/T/)
    })
})
