import { describe, expect, it } from 'vitest'

import { normalizeParserCapabilities } from '../src/lib/parser-capabilities.ts'

describe('parser capability normalization', () => {
    it('normalizes yt-dlp-like video formats', () => {
        const result = normalizeParserCapabilities({
            title: 'Example',
            formats: [
                { format_id: '140', acodec: 'mp4a', vcodec: 'none', ext: 'm4a' },
                { format_id: '137', height: 1080, fps: 30, vcodec: 'avc1', acodec: 'none', ext: 'mp4', url: 'https://cdn.example.com/1080' },
                { format_id: '399', height: 1080, fps: 60, vcodec: 'av01', acodec: 'none', ext: 'mp4', url: 'https://cdn.example.com/1080-60' },
                { quality: '720', height: 720, ext: 'mp4' },
            ],
        })

        expect(result.qualityOptions).toHaveLength(3)
        expect(result.qualityOptions?.[0]).toMatchObject({
            quality: '1080',
            height: 1080,
            formatId: 137,
            downloadUrl: 'https://cdn.example.com/1080',
        })
        expect(result.qualityOptions?.some((item) => item.quality === '720')).toBe(true)
    })

    it('normalizes manual and automatic caption maps', () => {
        const result = normalizeParserCapabilities({
            subtitles: {
                en: [{ url: 'https://cdn.example.com/en.vtt', ext: 'vtt', name: 'English' }],
            },
            automatic_captions: {
                zh: [{ url: 'https://cdn.example.com/zh.vtt', ext: 'vtt', name: '中文' }],
            },
        })

        expect(result.subtitles).toHaveLength(2)
        expect(result.subtitles?.[0]).toMatchObject({ language: 'en', label: 'English', format: 'vtt' })
        expect(result.subtitles?.[1]).toMatchObject({ language: 'zh', label: '中文', isAutoGenerated: true })
    })

    it('keeps already normalized capability fields', () => {
        const result = normalizeParserCapabilities({
            qualityOptions: [{ quality: '2160', height: 2160, label: '4K' }],
            subtitles: [{ language: 'ja', downloadUrl: 'https://cdn.example.com/ja.ass', format: 'ass' }],
        })

        expect(result.qualityOptions?.[0]).toMatchObject({ quality: '2160', height: 2160, label: '4K' })
        expect(result.subtitles?.[0]).toMatchObject({ language: 'ja', downloadUrl: 'https://cdn.example.com/ja.ass' })
    })
})
