(() => {
  'use strict'
  const $ = (id) => document.getElementById(id)
  const state = { status: null, jobs: [], token: sessionStorage.getItem('galaxy.headless.token') || '', view: 'dashboard', sortKey: 'createdAt', sortDirection: 'desc', refreshTimer: 0, eventController: null }
  const terminal = new Set(['completed', 'failed', 'cancelled'])
  const active = new Set(['preparing', 'downloading', 'merging', 'postprocessing'])
  const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]))
  const title = (j) => j.fileName || j.sourceHost || `Job ${String(j.id || '').slice(0, 8)}`
  const progressValue = (j) => Math.max(0, Math.min(Number(j.progress) || 0, 100))

  function requestHeaders(extra = {}) { const h = { Accept: 'application/json', ...extra }; if (state.token) h.Authorization = `Bearer ${state.token}`; return h }
  async function api(path, options = {}) {
    const response = await fetch(path, { ...options, headers: requestHeaders(options.headers || {}), cache: 'no-store' })
    if (response.status === 401) { showCredentials(true); setConnection(false, 'Authentication required'); throw new Error('Headless API requires a valid Bearer token') }
    const payload = await response.json().catch(() => ({}))
    if (!response.ok) throw new Error(payload.error || `Request failed (${response.status})`)
    return payload
  }
  function setConnection(ok, label) { $('connectionDot').classList.toggle('online', ok); $('connectionDot').classList.toggle('offline', !ok); $('connectionLabel').textContent = label }
  function showCredentials(force) { const panel = $('credentialsPanel'); const show = force === undefined ? panel.classList.contains('is-hidden') : Boolean(force); panel.classList.toggle('is-hidden', !show); if (show) { $('tokenInput').value = state.token; $('tokenInput').focus() } }
  function showError(message) { $('errorText').textContent = message || ''; $('errorNotice').classList.toggle('is-hidden', !message) }
  function formatDate(value) { if (!value) return '—'; const d = new Date(value); return Number.isNaN(d.getTime()) ? '—' : new Intl.DateTimeFormat(undefined, { month: 'short', day: '2-digit', hour: '2-digit', minute: '2-digit' }).format(d) }
  function badge(j) { const value = String(j.state || 'unknown'); return `<span class="state" data-state="${esc(value)}">${esc(value)}</span>` }
  function progress(j) { const value = progressValue(j); return `<div class="progress-cell"><div class="progress-track" aria-hidden="true"><div class="progress-bar" style="width:${value}%"></div></div><span class="progress-number">${value.toFixed(1)}%</span></div>` }
  function actions(j) { const id = esc(j.id); const out = []; if (['queued', 'preparing', 'downloading'].includes(j.state)) out.push(`<button class="action" data-action="pause" data-id="${id}" type="button">Pause</button>`); if (j.state === 'paused') out.push(`<button class="action" data-action="resume" data-id="${id}" type="button">Resume</button>`); if (j.state === 'failed') out.push(`<button class="action" data-action="retry" data-id="${id}" type="button">Retry</button>`); if (!terminal.has(j.state)) out.push(`<button class="action" data-action="cancel" data-id="${id}" type="button">Cancel</button>`); return out.join('') || '<span class="muted">—</span>' }

  function sortedJobs() {
    const key = state.sortKey
    const value = (j) => key === 'title' ? title(j).toLowerCase() : key === 'progress' ? progressValue(j) : key === 'createdAt' ? Date.parse(j.createdAt || '') || 0 : String(j[key] || '').toLowerCase()
    return [...state.jobs].sort((a, b) => { const av = value(a), bv = value(b); const order = typeof av === 'number' ? av - bv : String(av).localeCompare(String(bv)); return state.sortDirection === 'asc' ? order : -order })
  }
  function renderSort() { document.querySelectorAll('[data-sort-header]').forEach((th) => th.removeAttribute('aria-sort')); document.querySelectorAll('[data-sort]').forEach((b) => { const selected = b.dataset.sort === state.sortKey; b.dataset.direction = selected ? state.sortDirection : ''; if (selected) b.closest('th').setAttribute('aria-sort', state.sortDirection === 'asc' ? 'ascending' : 'descending') }) }
  function renderMetrics() { const count = (s) => state.jobs.filter((j) => j.state === s).length; $('metricEngine').textContent = state.status ? 'Online' : '—'; $('metricEngineDetail').textContent = state.status ? (state.status.version || state.status.service || 'Headless API v2') : 'Checking'; $('metricActive').textContent = state.jobs.filter((j) => active.has(j.state)).length; $('metricQueued').textContent = count('queued'); $('metricFailed').textContent = count('failed'); $('metricCompleted').textContent = count('completed') }
  function renderRecent() { const jobs = [...state.jobs].sort((a, b) => String(b.createdAt || '').localeCompare(String(a.createdAt || ''))).slice(0, 8); $('recentJobs').innerHTML = jobs.length ? jobs.map((j) => `<div class="recent-row">${badge(j)}<div class="title-cell"><div class="title-primary">${esc(title(j))}</div><div class="title-secondary">${esc(j.sourceHost || '')}</div></div>${progress(j)}<time class="numeric">${esc(formatDate(j.createdAt))}</time></div>`).join('') : '<div class="empty">No download jobs yet.</div>' }
  function renderDownloads() {
    $('downloadCount').textContent = `${state.jobs.length} job${state.jobs.length === 1 ? '' : 's'}`
    const jobs = sortedJobs(); $('downloadsBody').innerHTML = jobs.length ? jobs.map((j) => `<tr><td>${badge(j)}</td><td><div class="title-cell"><div class="title-primary">${esc(title(j))}</div><div class="title-secondary">${esc(j.detail || j.id)}</div></div></td><td>${progress(j)}</td><td class="numeric muted">—</td><td class="numeric muted">—</td><td class="numeric muted">—</td><td>${esc(j.sourceHost || '—')}</td><td class="numeric">${esc(formatDate(j.createdAt))}</td><td><div class="table-actions">${actions(j)}</div></td></tr>`).join('') : '<tr><td colspan="9"><div class="empty">No downloads. Submit a job through the API or Desktop handoff to see it here.</div></td></tr>'
    $('pauseAllButton').disabled = !state.jobs.some((j) => ['queued', 'preparing', 'downloading'].includes(j.state)); $('resumeAllButton').disabled = !state.jobs.some((j) => j.state === 'paused'); $('retryFailedButton').disabled = !state.jobs.some((j) => j.state === 'failed'); renderSort()
  }
  function render() { renderMetrics(); renderRecent(); renderDownloads() }
  async function refresh({ quiet = false } = {}) { if (!quiet) $('refreshButton').disabled = true; try { const [status, jobs] = await Promise.all([api('/v1/status'), api('/v1/jobs')]); state.status = status; state.jobs = Array.isArray(jobs.jobs) ? jobs.jobs : []; render(); setConnection(true, 'Connected'); showError(''); if (!$('credentialsPanel').classList.contains('is-hidden') && state.token) showCredentials(false) } catch (e) { showError(e instanceof Error ? e.message : 'Unable to load Headless API'); if (!String(e).includes('Bearer token')) setConnection(false, 'Disconnected') } finally { $('refreshButton').disabled = false } }
  function scheduleRefresh() { clearTimeout(state.refreshTimer); state.refreshTimer = setTimeout(() => refresh({ quiet: true }), 180) }
  async function runAction(id, action) { try { await api(`/v1/jobs/${encodeURIComponent(id)}/${action}`, { method: 'POST' }); await refresh({ quiet: true }) } catch (e) { showError(e instanceof Error ? e.message : 'Action failed') } }
  async function batchAction(action, predicate) { for (const j of state.jobs.filter(predicate)) { try { await api(`/v1/jobs/${encodeURIComponent(j.id)}/${action}`, { method: 'POST' }) } catch (e) { showError(e instanceof Error ? e.message : 'Batch action failed'); break } } await refresh({ quiet: true }) }
  function switchView(view) { state.view = view === 'downloads' ? 'downloads' : 'dashboard'; $('dashboardView').classList.toggle('is-hidden', state.view !== 'dashboard'); $('downloadsView').classList.toggle('is-hidden', state.view !== 'downloads'); $('viewTitle').textContent = state.view === 'downloads' ? 'Downloads' : 'Dashboard'; document.querySelectorAll('[data-view]').forEach((b) => b.classList.toggle('is-active', b.dataset.view === state.view)) }
  async function connectEvents() { if (state.eventController) state.eventController.abort(); const controller = new AbortController(); state.eventController = controller; try { const response = await fetch('/v1/events', { headers: requestHeaders(), cache: 'no-store', signal: controller.signal }); if (response.status === 401) { showCredentials(true); return } if (!response.ok || !response.body) throw new Error(`Events unavailable (${response.status})`); const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = ''; while (!controller.signal.aborted) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const frames = buffer.split('\n\n'); buffer = frames.pop() || ''; if (frames.some((frame) => frame.split('\n').some((line) => line.startsWith('data:')))) scheduleRefresh() } } catch { if (!controller.signal.aborted) setTimeout(connectEvents, 2500); return } if (!controller.signal.aborted) setTimeout(connectEvents, 500) }

  document.addEventListener('click', (event) => { const view = event.target.closest('[data-view]'); if (view) switchView(view.dataset.view); const jump = event.target.closest('[data-view-jump]'); if (jump) switchView(jump.dataset.viewJump); const action = event.target.closest('[data-action]'); if (action) runAction(action.dataset.id, action.dataset.action); const sort = event.target.closest('[data-sort]'); if (sort) { const key = sort.dataset.sort; state.sortDirection = state.sortKey === key && state.sortDirection === 'asc' ? 'desc' : 'asc'; state.sortKey = key; renderDownloads() } })
  $('refreshButton').addEventListener('click', () => refresh()); $('retryButton').addEventListener('click', () => refresh()); $('credentialsButton').addEventListener('click', () => showCredentials())
  $('credentialsForm').addEventListener('submit', (event) => { event.preventDefault(); state.token = $('tokenInput').value.trim(); if (state.token) sessionStorage.setItem('galaxy.headless.token', state.token); else sessionStorage.removeItem('galaxy.headless.token'); showCredentials(false); refresh(); connectEvents() })
  $('clearTokenButton').addEventListener('click', () => { state.token = ''; sessionStorage.removeItem('galaxy.headless.token'); $('tokenInput').value = ''; refresh(); connectEvents() })
  $('pauseAllButton').addEventListener('click', () => batchAction('pause', (j) => ['queued', 'preparing', 'downloading'].includes(j.state))); $('resumeAllButton').addEventListener('click', () => batchAction('resume', (j) => j.state === 'paused')); $('retryFailedButton').addEventListener('click', () => batchAction('retry', (j) => j.state === 'failed'))
  switchView('dashboard'); refresh(); connectEvents(); setInterval(() => refresh({ quiet: true }), 15000)
})()
