/**
 * Cloudflare Worker entry point — auto-generated by vinext deploy.
 * Edit freely or delete to regenerate on next deploy.
 *
 * For apps without image optimization, you can use vinext/server/app-router-entry
 * directly in wrangler.jsonc: "main": "vinext/server/app-router-entry"
 */
import { handleImageOptimization, DEFAULT_DEVICE_SIZES, DEFAULT_IMAGE_SIZES } from "vinext/server/image-optimization";
import handler from "vinext/server/app-router-entry";

interface WorkerFetcher {
  fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

interface DurableObjectStorageLike {
  get<T>(key: string): Promise<T | undefined>;
  put<T>(key: string, value: T): Promise<void>;
}

interface DurableObjectStateLike {
  storage: DurableObjectStorageLike;
}

interface DurableObjectStubLike {
  fetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response>;
}

interface DurableObjectNamespaceLike {
  idFromName(name: string): unknown;
  get(id: unknown): DurableObjectStubLike;
}

interface Env {
  ASSETS: WorkerFetcher;
  PARSE_STATS: DurableObjectNamespaceLike;
  IMAGES: {
    input(stream: ReadableStream): {
      transform(options: Record<string, unknown>): {
        output(options: { format: string; quality: number }): Promise<{ response(): Response }>;
      };
    };
  };
}

interface ExecutionContext {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
}

interface ParseStatsRecord {
  date: string;
  todayCount: number;
  totalCount: number;
}

const STATS_TIMEZONE = "UTC+08:00";
const STATS_TIMEZONE_OFFSET_MS = 8 * 60 * 60 * 1000;
const DAY_MS = 24 * 60 * 60 * 1000;

function resolveStatsWindow(now = new Date()) {
  const shifted = new Date(now.getTime() + STATS_TIMEZONE_OFFSET_MS);
  const date = shifted.toISOString().slice(0, 10);
  const shiftedDayStartMs = Date.parse(`${date}T00:00:00.000Z`);
  const windowStartMs = shiftedDayStartMs - STATS_TIMEZONE_OFFSET_MS;

  return {
    date,
    timezone: STATS_TIMEZONE,
    windowStart: new Date(windowStartMs).toISOString(),
    windowEnd: new Date(windowStartMs + DAY_MS).toISOString(),
  };
}

function parseStatsResponse(record: ParseStatsRecord | undefined, now = new Date()): Response {
  const window = resolveStatsWindow(now);
  const todayCount = record?.date === window.date ? record.todayCount : 0;
  const totalCount = record?.totalCount ?? 0;

  return Response.json({
    success: true,
    data: {
      ...window,
      count: todayCount,
      totalCount,
    },
  }, {
    headers: {
      "cache-control": "private, no-store",
    },
  });
}

/**
 * First-party Galaxy parse counter.
 *
 * One globally named Durable Object owns the counter, so all Worker isolates
 * observe the same values. Counts start when this binding is first deployed;
 * historical values from the old shared API are intentionally not imported.
 */
export class ParseStats {
  private readonly state: DurableObjectStateLike;

  constructor(state: DurableObjectStateLike) {
    this.state = state;
  }

  async fetch(request: Request): Promise<Response> {
    if (request.method === "GET") {
      const record = await this.state.storage.get<ParseStatsRecord>("counts");
      return parseStatsResponse(record);
    }

    if (request.method === "POST") {
      const window = resolveStatsWindow();
      const existing = await this.state.storage.get<ParseStatsRecord>("counts");
      const next: ParseStatsRecord = {
        date: window.date,
        todayCount: existing?.date === window.date ? existing.todayCount + 1 : 1,
        totalCount: (existing?.totalCount ?? 0) + 1,
      };
      await this.state.storage.put("counts", next);
      return parseStatsResponse(next);
    }

    return Response.json({ success: false, error: "Method not allowed" }, {
      status: 405,
      headers: {
        allow: "GET, POST",
        "cache-control": "private, no-store",
      },
    });
  }
}

function withLocalProcessingHeaders(response: Response): Response {
  const headers = new Headers(response.headers);

  // SharedArrayBuffer and multi-thread ffmpeg.wasm require cross-origin
  // isolation. `credentialless` is intentionally used instead of a global
  // `require-corp` policy because Galaxy renders third-party media artwork.
  // Browsers that do not support this COEP mode simply remain on the existing
  // single-thread FFmpeg fallback.
  headers.set("Cross-Origin-Opener-Policy", "same-origin");
  headers.set("Cross-Origin-Embedder-Policy", "credentialless");
  headers.set("Origin-Agent-Cluster", "?1");

  // Same-origin static resources can participate in an isolated document.
  headers.set("Cross-Origin-Resource-Policy", "same-origin");

  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

function isDailymotionHlsUrl(url: URL): boolean {
  return url.pathname === "/api/local-media"
    && url.searchParams.get("platform") === "dailymotion"
    && url.searchParams.get("mode") === "hls";
}

function isDailymotionHlsAlias(url: URL): boolean {
  return url.pathname === "/api/hls-proxy"
    && url.searchParams.get("provider") === "dailymotion";
}

function toDailymotionLocalMediaRequest(request: Request): Request {
  const source = new URL(request.url);
  const target = new URL(source.toString());
  target.pathname = "/api/local-media";
  target.searchParams.delete("provider");
  target.searchParams.set("platform", "dailymotion");
  target.searchParams.set("mode", "hls");

  return new Request(target.toString(), {
    method: request.method,
    headers: request.headers,
    redirect: request.redirect,
    signal: request.signal,
  });
}

async function rewriteDailymotionPlaylistResponse(response: Response): Promise<Response> {
  const contentType = response.headers.get("content-type")?.toLowerCase() || "";
  if (!response.ok || (!contentType.includes("mpegurl") && !contentType.includes("vnd.apple.mpegurl"))) {
    return response;
  }

  const text = await response.text();
  const rewritten = text.replaceAll(
    "/api/local-media?platform=dailymotion&mode=hls&",
    "/api/hls-proxy?provider=dailymotion&",
  );
  const headers = new Headers(response.headers);
  headers.delete("content-length");
  headers.set("content-length", String(new TextEncoder().encode(rewritten).byteLength));
  headers.set("cache-control", "private, no-store");

  return new Response(rewritten, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

const worker = {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // Site-owned usage statistics stay on the Galaxy Worker and never hit the
    // legacy shared API. A single named Durable Object provides global counts.
    if (url.pathname === "/api/site-stats") {
      const id = env.PARSE_STATS.idFromName("galaxy-global-parse-stats");
      const response = await env.PARSE_STATS.get(id).fetch(request);
      return withLocalProcessingHeaders(response);
    }

    // Image optimization via Cloudflare Images binding.
    // The parseImageParams validation inside handleImageOptimization
    // normalizes backslashes and validates the origin hasn't changed.
    if (url.pathname === "/_vinext/image") {
      const allowedWidths = [...DEFAULT_DEVICE_SIZES, ...DEFAULT_IMAGE_SIZES];
      const response = await handleImageOptimization(request, {
        fetchAsset: (path) => env.ASSETS.fetch(new Request(new URL(path, request.url))),
        transformImage: async (body, { width, format, quality }) => {
          const result = await env.IMAGES.input(body).transform(width > 0 ? { width } : {}).output({ format, quality });
          return result.response();
        },
      }, allowedWidths);
      return withLocalProcessingHeaders(response);
    }

    // Galaxy's browser HLS downloader historically trusts `/api/hls-proxy`
    // child resources. Dailymotion needs a same-egress relay because its
    // signed streams can be tied to the network identity that produced the
    // metadata. Keep that compatibility path as a Worker-level alias instead
    // of adding another Next route, which avoids vinext route-table drift.
    if (isDailymotionHlsAlias(url)) {
      const internalRequest = toDailymotionLocalMediaRequest(request);
      const response = await handler.fetch(internalRequest, env, ctx);
      return withLocalProcessingHeaders(await rewriteDailymotionPlaylistResponse(response));
    }

    // Root Dailymotion HLS playlists are served by the stable local-media
    // route. Rewrite their child URIs to the trusted Worker alias above.
    if (isDailymotionHlsUrl(url)) {
      const response = await handler.fetch(request, env, ctx);
      return withLocalProcessingHeaders(await rewriteDailymotionPlaylistResponse(response));
    }

    // Delegate everything else to vinext, forwarding ctx so that
    // ctx.waitUntil() is available to background cache writes and
    // other deferred work via getRequestExecutionContext().
    return withLocalProcessingHeaders(await handler.fetch(request, env, ctx));
  },
};

export default worker;
